-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1:3306
-- Время создания: Июл 30 2021 г., 20:13
-- Версия сервера: 5.7.29
-- Версия PHP: 7.4.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `online_store`
--

-- --------------------------------------------------------

--
-- Структура таблицы `products`
--

CREATE TABLE `products` (
  `id` int(11) UNSIGNED NOT NULL,
  `title` varchar(21) NOT NULL,
  `announce` varchar(250) NOT NULL,
  `text` text NOT NULL,
  `img` varchar(50) NOT NULL,
  `price` float UNSIGNED NOT NULL,
  `category` varchar(30) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `products`
--

INSERT INTO `products` (`id`, `title`, `announce`, `text`, `img`, `price`, `category`) VALUES
(1, 'Кроссовки мужские', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'footwear/fb-black-cross.jfif', 400, 'footwear'),
(2, 'Сапоги женские', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'footwear/fg-black-shoes.jfif', 600, 'footwear'),
(3, 'Кроссовки мужские', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'footwear/fb-blue-cross.jfif', 500, 'footwear'),
(4, 'Кроссовки мужские', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'footwear/un-black-cross.jfif', 350, 'footwear'),
(5, 'Туфли мужские', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'footwear/fb-light-shoes.jfif', 300, 'footwear'),
(6, 'Кроссовки женские', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'footwear/fg-black-cross.jfif', 400, 'footwear'),
(7, 'Кепка мужская', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'hats/fb-grey-pb.jfif', 200, 'hats'),
(8, 'Панама женская', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'hats/fg-pink-p.jfif', 350, 'hats'),
(9, 'Панама женская', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'hats/fg-sol-p.jfif', 300, 'hats'),
(10, 'Панама универсальная', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'hats/un-black-p.jfif', 250, 'hats'),
(11, 'Панама универсальная', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'hats/un-light-p.jfif', 400, 'hats'),
(12, 'Панама с принтом', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maximeтprovident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'hats/un-mar-p.jfif', 450, 'hats'),
(13, 'Футболка мужская', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'shirts/fb-bb.jfif', 400, 'shirts'),
(14, 'Футболка мужская', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'shirts/fb-p.jfif', 450, 'shirts'),
(15, 'Футболка женская', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'shirts/fg-b-wp.jfif', 300, 'shirts'),
(16, 'Футболка женская', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'shirts/fg-rb.jfif', 320, 'shirts'),
(17, 'Футболка мужская', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'shirts/un-b-ws.jfif', 300, 'shirts'),
(18, 'Футболка мужская', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'shirts/un-w.jfif', 300, 'shirts'),
(19, 'Часы мужские темные', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'watches/fb-blue.jfif', 1100, 'watches'),
(20, 'Часы мужские светлые', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'watches/fb-light.jfif', 1200, 'watches'),
(21, 'Часы женские', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'watches/fg-white.jfif', 1000, 'watches'),
(22, 'Часы черные', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'watches/un-black.jfif', 1430, 'watches'),
(23, 'Часы универсальные', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'watches/un-grey.jfif', 1350, 'watches'),
(24, 'Часы светлые', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.\r\nLorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi doloremque et ipsum maxime provident recusandae sequi! Amet corporis delectus, deserunt earum inventore ipsum iure minus molestiae possimus, provident ratione veniam.', 'watches/un-light.jfif', 1250, 'watches');

-- --------------------------------------------------------

--
-- Структура таблицы `users`
--

CREATE TABLE `users` (
  `id` int(11) UNSIGNED NOT NULL,
  `name` varchar(40) NOT NULL,
  `email` varchar(80) NOT NULL,
  `password` varchar(255) NOT NULL,
  `image` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `id` (`id`);

--
-- Индексы таблицы `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=25;

--
-- AUTO_INCREMENT для таблицы `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
